services:
  e2e-oidc:
    build: .
    container_name: e2e-oidc
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
    volumes:
      - ./users.json:/app/users.json:ro
